### ISSUE TITLE
Research Auth with Gatekeeper

### ISSUE THREAD

**Issue by geooot** [tamu-datathon-org/Ouroboros#1]
Strip out the auth and replace it such that it derives its auth state from gatekeeper

**Comment by phulsechinmay** [comment]
Obos is heavily ingrained with Django based auth:
* Uses the Django `authenticate` function to validate volunteers in a serializer (here)[https://github.com/tamuhack-org/Ouroboros/blob/d1bafcdfaf6b54eaf7bf9a6720373e0bd3ec8855/hiss/volunteer/serializers.py]

**Comment by geooot** [comment]
@phulsechinmay do you think replacing that function with our own could let us integrate?

**Comment by phulsechinmay** [comment]
@geooot I'm looking for more places where they have used django authentication either implicitly or explicitly. Form a cursory glance, the authentication seems mostly Django heavy, so we might need to override/replace more than just that function.

**Comment by samarthdave** [comment]
This link seems promising:
[https://kite.com/blog/python/custom-django-authentication/](https://kite.com/blog/python/custom-django-authentication/)

**Comment by geooot** [comment]
Figure out by next monday if obos is o-bad or o-good
