### ISSUE TITLE
Checkout Email templates to make sure they are TD pretty

### ISSUE THREAD

**Issue by geooot** [tamu-datathon-org/Ouroboros#13]
- Change Text and Images
- Maybe get logistics input on specific emails (especially the "After getting accepted" email)
- The acceptance email (maybe RSVP email) should include "Next Steps" which tell them to join the slack and do other things (discuss).

**Comment by danielabreo** [comment]
Branch updated-emails

Need content:
hiss/templates/application/emails/confirmed.html (ETA: early September)

Completed:
hiss/templates/application/emails/approved.html
hiss/templates/application/emails/created.html
hiss/templates/application/emails/rejected.html
hiss/templates/registration/emails/activate.html
hiss/templates/registration/emails/password_reset.html

**Comment by geooot** [comment]
Final Email Looks So Far:

![image](https://user-images.githubusercontent.com/7832610/85190303-bd4f4880-b27c-11ea-925f-3ff91eab34ec.png)

![image](https://user-images.githubusercontent.com/7832610/85190308-c4765680-b27c-11ea-89fb-1120d6960f4e.png)

![image](https://user-images.githubusercontent.com/7832610/85190332-f2f43180-b27c-11ea-8392-baa0393188f7.png)

Interestingly the last email sent after RSVPing attaches a qr code lol
