### ISSUE TITLE
Admin users cannot login without a normal user logging out

### ISSUE THREAD

**Issue by phulsechinmay** [tamu-datathon-org/Ouroboros#17]
Django seems to throw CSRF errors when trying to login to the admin portal when a normal user is already logged in.
* Logging out and then retrying the admin portal login solves this problem

**Notes:**
* The `GatekeeperRemoteBackend.authenticate` function is called when the admin is trying to login, which probably returns the user object of the normal user currently signed in. This might be causing this bug

**Comment by geooot** [comment]
@phulsechinmay 
- I logged in to Gatekeeper in production (https://galaxy.tamudatathon.now.sh/auth/login)
- then went to /apply/admin (https://galaxu.tamudatathon.now.sh/apply/admin)
- and got this: ![image](https://user-images.githubusercontent.com/7832610/84180746-a2473200-aa4d-11ea-9cc2-6b7df2b99869.png)

Maybe if we set the [user to be "is_staff"](https://github.com/tamu-datathon-org/Ouroboros/blob/master/hiss/user/models.py#L27) when we authenticate (if they are `isAdmin` from gatekeeper) we can have our own accounts be IsAdmin and it will let them access the admin portal?

**Comment by phulsechinmay** [comment]
@geooot That could fix it but still seems like a workaround. I believe the problem is that when a non-admin user is logged in, the `GatekeeperRemoteUserBackend` still returns the normal user which Django cannot use because they're not superusers. 

But we can look into this later, for now can just set our account as staff.
