### ISSUE TITLE
Research Obos Customization

### ISSUE THREAD

**Issue by geooot** [tamu-datathon-org/Ouroboros#2]
- Figure out how to customize obos to have our strings ("TAMU Datathon 2020", etc)
- Figure out how their views are setup (handlebars, partials, where their styles are)
- Figure out how to make a form

**Comment by samarthdave** [comment]
## 1) Customize strings & generalize content

generic variable strings:
look in
```
hiss/hiss/settings/customization.py
```

## Views setup (templating engine)

### 2) Django structure breakdown

|                      | Data Layer | Visual (html) | Brains         |
|----------------------|------------|---------------|----------------|
| Rails, Express, etc. | M          | V (view)      | C (controller) |
| Django               | M          | T (template)  | V (view)       |

- styling: they used raw css, we could swap in a sass bundler easily to output to the following path:
```
hiss/static/style.css
```

- Django appears to use similar templating in html files to ejs

### 3) Forms

- "views" are "templates" in Django and are in /hiss/templates.
- here is the signup form (embedded in Bootstrap HTML structure)
```html
<div class="col-sm-12 col-md-8 col-lg-6 login-box">

    <header>
        <img class="header-logo" src="{% static 'th_bw.svg' %}">
        <h1>{{ event_name }} 2020 Application</h1>
    </header>

    <form method="POST">
        {% csrf_token %}
        <!-- security -->

        {{form.as_p}}
        <input type="submit" value="Register" class="btn btn-lg btn-block btn-login">
    </form>

    <div class="row login-alt-options pt-4">
        <div class="col-sm-12 col-lg-12 text-center">
            Already have an account? <a href="{% url 'customauth:login' %}">Log in</a>
        </div>
    </div>
</div>
```
