### ISSUE TITLE
Figure out how to get resume links to work

### ISSUE THREAD

**Issue by geooot** [tamu-datathon-org/Ouroboros#27]
Right now resume links don't work (see how it is programmed to be able to be accessed). Can we get these resumes to be put into a storage bucket?

**Comment by phulsechinmay** [comment]
Seems like we just need to change `MEDIA_URL = "resumes/"` to `MEDIA_URL = "/" + BASE_PATHNAME + "resumes/"`.

I've made this change in #30. If we want to upload this to an S3 bucket, might need to look into other stuff.
